### PR TITLE
Rename the opam package from travis-opam to ci-opam

### PR DESCRIPTION
**Pull request by kit-ty-kate**
The reasoning behind this is that the package doesn't match up with the binary name and even from its purpose.
However this is a little tricky since the package is already on opam and I'm not sure what the migration path between the two would be.

cc @samoht

### CODE REVIEW

**Comment by samoht** [comment]
LGTM although the Travis error seems to indicate that `OPAMYES` is needed somewhere.

I wouldn't worry too much about the transition path, these packages are mainly used in the docker images (that you fix in that PR already). So as long as these continue to work, I am fine.

**Comment by jpdeplaix** [comment]
Mmh this is really weird. ```OPAMYES``` is exported and there is even a ```-y``` given to the last command. I don't understand what has changed here :/

**Comment by samoht** [comment]
Maybe `opam pin` doesn't care about `OPAMYES` in opam2? /cc @AltGr

**Comment by XVilka** [comment]
There are conflicts @kit-ty-kate. And some unsolved problems. Does it really worth it? Maybe it's better to close this one?

**Comment by dra27** [comment]
For opam-repository, the fix could be done similarly to jbuilder - add a `travis-opam.transitional` package depending on the new `ci-opam`?

**Pull request closed without merging**
