### PR TITLE
Use final version of 4.14 and add 5.0

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Is travis still used? I thought it went down for everyone

**Comment by edwintorok** [comment]
FWIW we've switched the XAPI project over to use GitHub actions instead.

**Comment by Leonidas-from-XIV** [comment]
I have no idea, I have switched all projects that I actively use to OCaml-CI or Github Actions, so this was just "might as well update this while at it".

**Comment by kit-ty-kate** [comment]
sure, yolo. Thanks

**Pull request merged**
