### PR TITLE
Add a license file

### PR DESCRIPTION
**Pull request by samoht**
See #201 

I guess this will need to be ack-ed by all the contributors:

- [x] @samoht 
- [x] @mor1 
- [x] @dsheets 
- [x] @avsm 
- [x] @edwintorok 
- [x] @simonjbeaumont 
- [x] @yallop 
- [x] @hannesm 
- [x] @yomimono 
- [x] @Leonidas-from-XIV 
- [x] @Chris00 
- [x] @fdopen 
- [x] @euanh 
- [x] @seliopou 
- [x] @djs55 
- [x] @talex5 
- [x] @infidel 
- [x] @gasche 
- [x] @toots 
- [ ] @ymyzk 
- [x] @MagnusS 
- [x] @fgimenez 
- [x] @andyli

### CODE REVIEW

**Comment by yomimono** [comment]
Acknowledged; I agree to this.

**Comment by mor1** [comment]
I don't seem to be able to check the checkbox so: I hereby ack this. I'm fine with my contribs to this repo being put under ISC license.

**Comment by yallop** [comment]
ack

**Comment by toots** [comment]
Sure!

**Comment by seliopou** [comment]
ack

**Comment by simonjbeaumont** [comment]
Ack

**Comment by hannesm** [comment]
sure (also updated the checkmarks)

**Comment by fgimenez** [comment]
Ack

**Comment by fdopen** [comment]
Ack

**Comment by gasche** [comment]
Ack :-)

**Comment by Leonidas-from-XIV** [comment]
Ack

**Comment by Chris00** [comment]
Ack.

**Comment by edwintorok** [comment]
Ack.

**Comment by avsm** [comment]
Ack.

**Comment by MagnusS** [comment]
Ack

**Comment by talex5** [comment]
Ack

**Comment by andyli** [comment]
Ack

**Comment by djs55** [comment]
Ack

**Comment by dsheets** [comment]
Ack

**Comment by euanh** [comment]
Ack

**Comment by infidel** [comment]
Ack

**Comment by hannesm** [comment]
dear @ymyzk, would you be so kind to agree or disagree on this PR, please?  the other 22 contributors all agreed on that license.  thanks!

**Comment by avsm** [comment]
We can go ahead and merge this. I've looked at f5b7ce82be7ee2697c9990c6bd3ac5be9c85b8ee which is the @ymyzk contribution, and it is a whitespace change and so doesn't need to be considered  as part of the licensing change proposed here.  Thanks everyone for acking this so quickly!

**Pull request merged**
