### PR TITLE
Use opam-package-upgrade instead of opam-show to update opam files

### PR DESCRIPTION
**Pull request by rjbou**
opam-package-upgrade 0.2 takes also descr & url files  to do the upgrade.
**NOT** to merge ftm, until https://github.com/AltGr/opam-package-upgrade/pull/2 merged & 0.2 version released.

This fixes  travis errors on #257.

Note that it adds opam-libs deps to `travis` package.

### CODE REVIEW

**Comment by samoht** [comment]
What's the status of this one? Any ETA for a release of opam-package-upgrade?

**Comment by samoht** [comment]
ping

**Comment by XVilka** [comment]
Should be rebased if there is still interest in this PR.

**Comment by rjbou** [comment]
Rebased!

**Comment by XVilka** [comment]
Any decision with this one?

**Comment by XVilka** [comment]
Would be nice to have https://github.com/AltGr/opam-package-upgrade/pull/4 merged before to prevent blocking Dune 2.0

**Comment by XVilka** [comment]
The only one missing piece left - the release of the new version of opam-package-upgrade: https://github.com/AltGr/opam-package-upgrade/issues/5
@rjbou @AltGr

**Comment by XVilka** [comment]
Looks like a problem in the opam-format:
```
#=== ERROR while compiling opam-format.2.0.6 ==================================#
# context     2.0.6 | linux/x86_64 | ocaml-base-compiler.4.10.0 | git://github.com/ocaml/opam-repository
# path        ~/.opam/ocaml-base-compiler.4.10.0/.opam-switch/build/opam-format.2.0.6
# command     ~/.opam/opam-init/hooks/sandbox.sh build make opam-format.install
# exit-code   2
# env-file    ~/.opam/log/opam-format-15190-913ef4.env
# output-file ~/.opam/log/opam-format-15190-913ef4.out
### output ###
# [...]
# File "src/format/opamFilter.ml", line 111, characters 18-28:
# 111 |             (fst (Re.get_ofs ss 0) + String.length (Re.get ss 0))
#                         ^^^^^^^^^^
# Alert deprecated: Re.get_ofs
# Use Group.offset
# File "src/format/opamFilter.ml", line 111, characters 52-58:
# 111 |             (fst (Re.get_ofs ss 0) + String.length (Re.get ss 0))
#                                                           ^^^^^^
# Alert deprecated: Re.get
# Use Group.get
# Makefile:104: recipe for target 'opam-format.install' failed
# make: *** [opam-format.install] Error 1
```

**Comment by hannesm** [comment]
I pushed a commit here to preserve the `opam-package-upgrade` binary (before opam remove travis-opam is executed). There's still an issue with 4.10, as @XVilka pointed out. An upstream fix is in https://github.com/ocaml/opam/pull/4115 -- but I'm not sure how/whether to fix the released opam versions (that's why I asked on the opam PR whether the fix should be backported and a 2.0.7 being released).

**Comment by kit-ty-kate** [comment]
I'm not sure this change is worth the extra 5 to 10 minutes per os/platform/ocaml-version/jobs/...

Would it be ok to close this? Do you know anybody requiring this?

**Comment by hannesm** [comment]
I'm fine with closing this -- it was an idea for the opam 1 -> opam 2 migration period, which is pretty much over these days (I barely see any opam 1 files around).

**Pull request closed without merging**
