### PR TITLE
change OCAML_VERSION=4.07 to use 4.07.1

### PR DESCRIPTION
**Pull request by jonsterling**

### CODE REVIEW

**Comment by samoht** [comment]
Thanks!

**Comment by jonsterling** [comment]
@samoht Hmm, even though t his is merged, when I run this script I find that 4.07.0 is used; I guess this change was not sufficient?

**Comment by samoht** [comment]
@jonsterling do you have a trace where this is still using 4.07.0? Maybe the Docker images needs to be updated as well.

**Comment by jonsterling** [comment]
@samoht Sure, here you go! https://travis-ci.org/RedPRL/redtt/builds/444128151?utm_source=github_status&utm_medium=notification

**Comment by jonsterling** [comment]
@samoht Just to update you, this seems fixed and working now! Thanks for whatever you did :smile:

**Pull request merged**
