### PR TITLE
Switch travis-docker to ocurrent images

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Just a draft for now. Need to ask around if it might break some setup.

Background post: https://discuss.ocaml.org/t/removing-fat-compiler-images-on-hub-docker-com-r-ocaml-opam2/6658/2

### CODE REVIEW

**Comment by hannesm** [comment]
yes please, thank you so much for this :)

**Comment by hannesm** [comment]
While I'm sure it will break some setup, I'd be in favour of merging this rather sooner than later. Maybe printing a URL to an issue in this repository on script failure will allow to point people to more information.

**Review by avsm — CHANGES_REQUESTED** [review]

**Comment by avsm** [comment]
Good by me to merge after the change to use ocaml/opam instead of ocurrent/opam. Thanks Kate!

**Review by hannesm — APPROVED** [review]
I applied @avsm suggestions, and would appreciate once CI is green to have someone (@kit-ty-kate or @avsm) pressing the green button.

**Pull request merged**
