### PR TITLE
Set latest opam to 2.0.6

### PR DESCRIPTION
**Pull request by XVilka**
I think also it makes sense to up the default version of the OCaml being tested. At least to 4.05, because the recommended version of the Ubuntu in Travis is Bionic, which has the 4.05 as the system version:
- https://docs.travis-ci.com/user/reference/overview/
- https://packages.ubuntu.com/source/bionic/ocaml

So if you are fine with that - we can up the CI version to Bionic and the `SYS_OCAML_VERSION` to 4.05.

### CODE REVIEW

**Comment by XVilka** [comment]
Blocked by https://github.com/ansible/ansible/issues/66618

**Comment by XVilka** [comment]
Answer from Ansible PPA (from which bubblewrap was installed):
> Just to note: that repo is a dependency repo for the Ansible Tower product, for the release supporting Ubuntu 16.04. It's not intended to be a general-purpose repo.
> I will check with that release team as to whether that's something that needs fixed in that respect, but if you're using it for some upstream CI, I strongly suggest moving to a different repo more directly tied to the bubblewrap project, or hosting your own. `ansible/bubblewrap` ppa likely will go away at some point when those releases of Ansible Tower are EOLed.

**Comment by XVilka** [comment]
Ok, now it is green - please check if it makes sense, thank you!

**Comment by XVilka** [comment]
So, what do you think?

**Comment by kit-ty-kate** [comment]
the problem with switching to bionic is that every projects that uses the script is going to break as they are currently not using bionic. I don't think we have any other solution than to follow the default distribution given by travis

**Comment by XVilka** [comment]
@kit-ty-kate so the PR is fine if I use Xenial instead, right? Since Trusty was deprecated by Travis and not a default one anyway.

**Comment by kit-ty-kate** [comment]
> @kit-ty-kate so the PR is fine if I use Xenial instead, right? Since Trusty was deprecated by Travis and not a default one anyway.

As long as the `.travis.yml` does not require any change, then yes.

**Comment by XVilka** [comment]
Ignore AppVeyor failure, it's unrelated and seems like this bug: https://github.com/ocaml/ocaml-ci-scripts/issues/325

**Comment by XVilka** [comment]
@kit-ty-kate could you please have a look again?

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
