### PR TITLE
use opam 2.0.1 by default

### PR DESCRIPTION
**Pull request by hannesm**
as suggested in https://github.com/ocaml/opam/issues/3548#issuecomment-431651465

it is unclear to me how the version numbering should work here:
- should there be a OPAM=2 which sticks to the latest release of opam (within major version 2)? (and/or OPAM=2.0 to specify the 2.0.X release series?)
- is there any need to specify exact versions (i.e. opam2.0.0, opam2.0.1)?
- when to phase out opam1 (1.1.2, 1.2.0, 1.2.2) support?

### CODE REVIEW

**Comment by samoht** [comment]
This unfortunately seems to be blocked on #258 to fix the lint error.

**Comment by samoht** [comment]
After discussion with @rjbou the proper fix for the lint error is:

- call `opam show -f opam-version: <pkg>`  to get the version of the opam file
- if it's 2.0, do as we do today
- if it's 1.0 disable error 57

**Comment by hannesm** [comment]
@samoht good to know, thanks. feel free to close this and do the right thing [tm] in another PR (this one also has merge conflicts with master now), or push to this PR directly.

**Comment by samoht** [comment]
@kit-ty-kate @dra27 can we merge this one? Or something still has to be done for the lint errors (sorry I haven't followed closely what happened here. Does someone else need merge rights to ease the process?

**Comment by kit-ty-kate** [comment]
sure, let's go.

**Comment by dra27** [comment]
I don't think this was meant to be merged?

**Comment by kit-ty-kate** [comment]
why?

**Comment by dra27** [comment]
Wasn’t switching the default to opam 2 supposed to be predicated on the lint issue being addressed?

**Comment by kit-ty-kate** [comment]
mmh I'm not sure to understand. It's only switching from 2.0.0 to 2.0.1 by default which is a pretty light change. The lint issue can be fixed afterwards.

**Comment by dra27** [comment]
opam 2.0.1 introduced lint warning 57, which needs to be disabled if the package being tested has an OPAM 1 opam file. I'm working on a fix...

**Comment by kit-ty-kate** [comment]
but afaik there was already another lint issue with opam1 package so it mostly doesn't change anything and improves travis for opam-repository (the macos issue with 2.0.0)

**Comment by dra27** [comment]
No - the switch from 2.0.0 to 2.0.1 has permanently broken a Travis build on Merlin

**Comment by kit-ty-kate** [comment]
ah, crap. Sorry about that :/

**Comment by dra27** [comment]
Don't worry - it's nearly fixed 🙂

**Pull request merged**
