### PR TITLE
add OCaml 4.06 support

### PR DESCRIPTION
**Pull request by andyli**

### CODE REVIEW

**Comment by yallop** [comment]
This looks similar to #189.

**Comment by andyli** [comment]
Ah, indeed. Didn't notice the other PR.
Mine doesn't conflict, and I've added 4.06 to this repo's .travis.yml.
But feel free to merge/close as you wish.

**Comment by yomimono** [comment]
@samoht (or anyone else with merge access), any chance of getting this PR or #189 merged soon?  If not, it would be nice to know whether there is a blocker and what we can do to resolve it.

**Comment by hannesm** [comment]
thanks!

**Comment by hannesm** [comment]
and sorry for the delay, I only today was granted write access to this repository

**Pull request merged**
