### PR TITLE
Render "with_fold" for AppVeyor

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
IMHO, `Yorick` could also use ANSI colors to output the commands.  That would make the log easier to read.

**Comment by edwintorok** [comment]
Nice, this should address https://github.com/ocaml/ocaml-ci-scripts/issues/131

**Comment by Chris00** [comment]
> the appveyor failure should go away if you rebase your branch on top of latest master

Did that.

**Comment by edwintorok** [comment]
Green now: https://ci.appveyor.com/project/edwintorok/ocaml-ci-scripts/build/1.0.29

**Comment by Chris00** [comment]
[Yorick] script was outputting non-printable chars when they were (because of bugs) present in the command arguments, [making the result confusing](https://ci.appveyor.com/project/Chris00/ocaml-mindstorm/build/1.0.276#L574) (see line 574).  The next commit [makes the situation better](https://ci.appveyor.com/project/Chris00/ocaml-mindstorm/build/1.0.278#L571) (line 571).

**Comment by Chris00** [comment]
As shown in the previous links, `\r` were present in package names on AppVeyor.  The following commit fixes that.

**Comment by Chris00** [comment]
I had other problems related to read-only files on Windows.  [They are fixed](https://gitlab.camlcity.org/gerd/lib-findlib/issues/15).

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
