### PR TITLE
Add branches for OCaml 4.07

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
Not sure how to test it, but maybe Travis can do it for me? Let's see!

### CODE REVIEW

**Comment by samoht** [comment]
Cool, thanks!

**Comment by samoht** [comment]
I think you need to update the `install_on_osx` instructions too.

**Comment by Leonidas-from-XIV** [comment]
This is a good catch. I've also updated the OCaml full version to match what is actually available in homebrew.

I'll submit a PR to homebrew-core so we can switch the system switch from 4.06.1 to 4.07.0.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/29940 shipped.

**Comment by Leonidas-from-XIV** [comment]
I don't know why sometimes the key 5B2D0C5561707B09 is missing, but I don't think it is this PR specifically which messed it up…

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
