### PR TITLE
 Remove opam 1.2 support and update homebrew support

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Fixes https://github.com/ocaml/ocaml-ci-scripts/issues/322 and https://github.com/ocaml/ocaml-ci-scripts/issues/326

cc @hannesm @XVilka

### CODE REVIEW

**Comment by XVilka** [comment]
It tries to download non-existing opam release:
```
+sudo wget https://github.com/ocaml/opam/releases/download/2/opam-2-x86_64-linux -O /usr/local/bin/opam
--2020-03-18 00:44:53--  https://github.com/ocaml/opam/releases/download/2/opam-2-x86_64-linux
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-18 00:44:53 ERROR 404: Not Found.
```

**Comment by kit-ty-kate** [comment]
Ok I think it's good as is. I've cancelled the macos jobs to not strain the CI too much as the last commit was very minimal.

**Comment by XVilka** [comment]
LGTM, but probably worth to use 4.09.1 instead of 4.09.0

**Comment by hannesm** [comment]
I'd be grateful to have this merged (since #326 is rather annoying for me) -- but I've not reviewed this diff, neither do I feel competent to do so

**Pull request merged**
